import type { Metadata } from "next";
import "./globals.css";
import { FormProvider } from "@/context/Context";
import { Toaster } from "react-hot-toast";



export const metadata: Metadata = {
  title: "EduBridge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" className="rounded-full " />
      </head>
      <body className={` font-Inter `}>
        <FormProvider >
        {children}
        <Toaster position="top-right" reverseOrder={false} />
        </FormProvider>
      </body>
    </html>
  );
}
