import { Footer } from "@/components/Footer";
import Header from "@/components/Header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "EduBridge Course",
  description: "Generated by create next app",
};

export default function CourseLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div>
    <Header />
    <div className=" min-h-[100vh] ">
      {children}
    </div>
    <Footer />
  </div>;
}
